# Generated by Django 2.0 on 2019-01-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U',
        ),
    ]
