# Generated by Django 2.0 on 2019-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
