# Generated by Django 2.0 on 2019-01-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0002_auto_20190114_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default='', max_length=32),
        ),
    ]
